"""auto-posts

Revision ID: ce0af5866531
Revises: 9244fb2d19db
Create Date: 2022-12-19 11:32:52.755860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0af5866531'
down_revision = '9244fb2d19db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
